run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - revive
    - misspell

linters-settings:
  errcheck:
    ignore: 'io:Close|fmt:Fprint|fmt:Fprintf|net:Close'

issues:
  exclude-rules:
    - linters: [errcheck]
      text: 'Error return value of `.*\.Close` is not checked'

    - linters: [errcheck]
      text: 'Error return value of `fmt\.(Fprint|Fprintf)` is not checked'

    - linters: [staticcheck]
      text: 'QF1012:'

    - linters: [staticcheck]
      text: 'QF1003:'

    - linters: [staticcheck]
      text: 'SA9003:'

  max-issues-per-linter: 0
  max-same-issues: 0